- name: OpenVPN service
  hosts: all
  sudo: true
  roles:
  - service

- name: OpenVPN TAP server
  hosts: tap_server
  sudo: true
  roles:
  - tap_server

- name: OpenVPN TAP clients
  hosts: tap_clients
  sudo: true
  roles:
  - tap_clients

- name: OpenVPN TUN server
  hosts: tun_server
  sudo: true
  roles:
  - tun_server

- name: OpenVPN TUN clients
  hosts: tun_clients
  sudo: true
  roles:
  - tun_clients
