- set_fact:
    openvpn_conf: /usr/local/etc/openvpn/
  when: ansible_distribution == 'FreeBSD'
- set_fact:
    openvpn_conf: /etc/openvpn/
  when: ansible_system == 'Linux'

- name: Create openvpn user
  user: >
    name=openvpn
    createhome=no
    comment=OpenVPN
    shell=/bin/false
    home=/etc/openvpn

- name: Install openvpn (Debian)
  when: ansible_distribution == 'Debian'
  apt: name=openvpn state=latest force=yes
- name: Install openvpn (CentOS)
  when: ansible_distribution == 'CentOS'
  yum: name=openvpn state=latest
- name: Install openvpn (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=openvpn state=present

- name: Remove example config
  file: path={{ openvpn_conf }}update-resolv-conf state=absent
- name: Paste client config
  notify: restart openvpn
  template: >
    src=client.conf
    dest={{ openvpn_conf }}client.conf
    owner=openvpn
    group=openvpn
    mode=0770
