 set_fact:
      openvpn_conf: /usr/local/etc/openvpn/
    when: ansible_distribution == 'FreeBSD'
  - set_fact:
      openvpn_conf: /etc/openvpn/
    when: ansible_system == 'Linux'

  - name: Create openvpn user
    user: >
      name=openvpn
      group=openvpn
      createhome=no
      comment=OpenVPN
      shell=/bin/false
      home=/etc/openvpn

- name: Install openvpn (debian)
  apt: name=openvpn state=latest
  notify: restart openvpn

- name: Remove example config
  file: path={{ openvpn_conf }}update-resolv-conf state=absent
- name: Paste client config
  notify: restart openvpn
  template: >
    src=client.conf
    dest={{ openvpn_conf }}client.conf
    owner=openvpn
    group=openvpn
    mode=0770
