- name: Set config file (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: >
    dest=/etc/rc.conf
    regexp=^openvpn_configfile=
    line=openvpn_configfile={{ openvpn_conf }}tap.conf

- name: Paste server config
  notify: restart openvpn
  template: >
    src=tap.conf
    dest={{ openvpn_conf }}tap.conf
    owner=openvpn
    group=openvpn
    mode=0770

- name: Creates client config directory
  file: >
    path={{ openvpn_conf }}tap_ccd
    state=directory
    owner=openvpn
    group=openvpn
    mode=0770
- name: Copy config for each client
  copy: >
    src={{ item }}
    dest={{ openvpn_conf }}tap_ccd
    owner=openvpn
    group=openvpn
    mode=0770
  with_fileglob:
  - ../templates/tap_ccd/*
