 set_fact:
      openvpn_conf: /usr/local/etc/openvpn/
    when: ansible_distribution == 'FreeBSD'
  - set_fact:
      openvpn_conf: /etc/openvpn/
    when: ansible_system == 'Linux'

- name: Install easy-rsa (debian)
  apt: name=easy-rsa state=latest
- name: Install openvpn (debian)
  apt: name=openvpn state=latest
  notify: restart openvpn

- name: Remove example config
  file: path={{ openvpn_conf }}update-resolv-conf state=absent
- name: Paste server config
  notify: restart openvpn
  template: >
    src=server.conf
    dest={{ openvpn_conf }}server.conf
    owner=openvpn
    group=openvpn
    mode=0770

- name: Creates client config directory
  file: path={{ openvpn_conf }}ccd state=directory
- name: Copy config for each client
  notify: reload openvpn
  copy: >
    src={{ item }}
    dest={{ openvpn_conf }}ccd
    owner=openvpn
    group=openvpn
    mode=0770
  with_fileglob:
  - ../templates/ccd/*
