- set_fact:
    openvpn_conf: /usr/local/etc/openvpn/
  when: ansible_distribution == 'FreeBSD'
- set_fact:
    openvpn_conf: /etc/openvpn/
  when: ansible_system == 'Linux'

- name: Create openvpn user
  user: >
    name=openvpn
    createhome=no
    comment=OpenVPN
    shell=/bin/false
    home=/etc/openvpn

- name: Install easy-rsa (debian)
  apt: name=easy-rsa state=latest

- name: Install openvpn (Debian)
  when: ansible_distribution == 'Debian'
  apt: name=openvpn state=latest force=yes
- name: Install openvpn (CentOS)
  when: ansible_distribution == 'CentOS'
  yum: name=openvpn state=latest
- name: Install openvpn (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=openvpn state=present

- name: Creates openvpn directory
  file: >
    path={{ openvpn_conf }}
    state=directory
    owner=openvpn
    group=openvpn
    mode=0770

- name: Enable openvpn service (CentOS)
  when: ansible_distribution == 'CentOS'
  service: name=openvpn@service.service enabled=yes
- name: Enable openvpn service (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^openvpn_enable= line=openvpn_enable=YES
- name: Enable openvpn interface (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^openvpn_if= line=openvpn_if=tun

- name: Remove example config
  file: path={{ openvpn_conf }}update-resolv-conf state=absent
- name: Paste server config
  notify: restart openvpn
  template: >
    src=server.conf
    dest={{ openvpn_conf }}server.conf
    owner=openvpn
    group=openvpn
    mode=0770

- name: Creates client config directory
  file: >
    path={{ openvpn_conf }}ccd
    state=directory
    owner=openvpn
    group=openvpn
    mode=0770
- name: Copy config for each client
  notify: reload openvpn
  copy: >
    src={{ item }}
    dest={{ openvpn_conf }}ccd
    owner=openvpn
    group=openvpn
    mode=0770
  with_fileglob:
  - ../templates/ccd/*
