- name: Set tap config file (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: >
    dest=/etc/rc.conf
    regexp=^openvpn_configfile=
    line=openvpn_configfile={{ openvpn_conf }}tap.conf

- name: Paste tap server config
  notify: restart openvpn
  template: >
    src=tap.conf
    dest={{ openvpn_conf }}tap.conf
    owner=openvpn
    group=openvpn
    mode=0770

- name: Creates tap client config directory
  file: >
    path={{ openvpn_conf }}tap_ccd
    state=directory
    owner=openvpn
    group=openvpn
    mode=0770
- name: Copy tap config for each client
  notify: reload openvpn
  copy: >
    src={{ item }}
    dest={{ openvpn_conf }}tap_ccd
    owner=openvpn
    group=openvpn
    mode=0770
  with_fileglob:
  - ../templates/tap_ccd/*

- name: Install easy-rsa (debian)
  apt: name=easy-rsa state=latest
