- set_fact:
    openvpn_conf: /usr/local/etc/openvpn/
  when: ansible_distribution == 'FreeBSD'
- set_fact:
    openvpn_conf: /etc/openvpn/
  when: ansible_system == 'Linux'

- name: Install openvpn (Debian)
  when: ansible_distribution == 'Debian'
  apt: name=openvpn state=latest force=yes
  notify: restart openvpn
- name: Install openvpn (CentOS)
  when: ansible_distribution == 'CentOS'
  yum: name=openvpn state=latest
  notify: restart openvpn
- name: Install openvpn (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  pkgng: name=openvpn state=present
  notify: restart openvpn

- name: Creates openvpn directory
  file:
    path={{ openvpn_conf }}
    state=directory
    owner=openvpn
    group=openvpn
    mode=0770

- name: Enable openvpn service (CentOS)
  when: ansible_distribution == 'CentOS'
  service: name=openvpn@client.service enabled=yes
- name: Enable openvpn service (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^openvpn_enable= line=openvpn_enable=YES
- name: Enable openvpn interface (FreeBSD)
  when: ansible_distribution == 'FreeBSD'
  lineinfile: dest=/etc/rc.conf regexp=^openvpn_if= line=openvpn_if=tap

- name: Remove example config
  file: path={{ openvpn_conf }}update-resolv-conf state=absent

- name: Install easy-rsa (debian)
  apt: name=easy-rsa state=latest
